Fix Aquilon README
quattor/aquilon pull request #36
Opened 2016-10-06 10:16 UTC by guillaume-philippon

Hi,

This PR is to fix documentation of Aquilon installation.

2016-10-06 10:36 UTC, ned21 commented
Notifying @ajf8 @gombasg

2017-03-21 11:19 UTC, gombasg commented
The ms.version.addpkg() parameters should not be changed - that would break our setup.

2017-03-21 11:26 UTC, guillaume-philippon commented
I remove all non-documentation modification

2017-03-21 16:42 UTC, jrha commented
LGTM

2017-03-21 16:43 UTC, jrha approved these changes

2017-03-21 16:44 UTC, guillaume-philippon commented
Not sure it s enough to build a working aquilon server. Perhaps, The PR must be a base for installation hand-on and fixe what still miss

2017-03-22 09:50 UTC, jouvin commented
March 17 workshop: complete and merge after the hands on session at the workshop

2017-03-23 08:19 UTC, jrha commented
Ideally this should be pulled in to a MS branch for internal review and pushed back to Github from there.

2017-03-23 08:20 UTC, jrha commented on README.md
> +If the installation is done as root and all the dependencies (liste in `/opt/aquilon/setup.py` have been installed
liste**d**

2017-03-23 08:22 UTC, jrha commented on README.md
> +as RPM or using the `pip` command, there is no more installation steps to do and you should be able to run the
there **are** no more

2017-03-23 08:23 UTC, jrha commented on README.md
> + * `cdb` package installed as a RPM will be reported as missing but it should not prevent the installation to work
installation **from** work**ing**

2017-03-23 08:25 UTC, jrha commented on README.md
> +Be sure to definie properly the domain associated with your realm: it must match your actual
properly defin~i~e

2017-03-23 08:25 UTC, jrha commented on README.md
> +It is recommended not to run the broker as root. This is causing quite a number of problem with
This ~is~ caus**es**

2017-03-23 08:39 UTC, jouvin commented
@guillaume-philippon I let you fix the typos, it would be easier.

2017-03-23 09:50 UTC, guillaume-philippon commented
I m waiting the feedback of @samary and @rhumroux before pushing the typo fix

2017-03-23 21:09 UTC, jouvin commented
@guillaume-philippon you forgot to merge my PR to your branch with the cleanup I did yesterday evening... I guess I need to rebase it... I'm checking right now.

2017-03-23 21:17 UTC, jouvin requested changes

2017-03-23 21:17 UTC, jouvin commented on README.md
> +It is recommended not to run the broker as root. This cause quite a number of problem with
causeS

2017-03-23 21:20 UTC, jouvin commented
[PR](https://github.com/guillaume-philippon/aquilon/pull/3) on your source branch has been rebased on this PR and can be merged.

2017-03-23 21:30 UTC, jouvin approved these changes

2017-03-23 21:31 UTC, jouvin commented
It seems you need to rebase the PR on the last version of master as there is a conflict with `.gitignore`.

2017-03-23 21:36 UTC, jouvin commented
We still need to fix the Git initialization when you are back and after testing it again. I merge this PR as it is already a good start and we'll fix the last point in a future PR.

2017-03-23 21:36 UTC, merged

2017-03-23 21:37 UTC, ned21 commented
@jouvin I don't think you can just merge things onto this branch. These commits will get lost the next time there's a push from our internal repo. We need Gabor and Dave to determine the correct way for us to accept these patches.

2017-03-23 21:53 UTC, jouvin commented
@ned21 sorry, I forgot this detail... I really apologize for that. At the same time, we need to expose a better installation documentation so I'd suggest to keep it merged and saved somewhere else (I have it in my fork and clone anyway). These changes should not conflict with MS development as I think the README file has been maintained mainly by us in fact...).

2017-03-23 22:21 UTC, ned21 commented
@jouvin Definitely! Dave is out tomorrow but I'll sync up with him next week and we'll start meeting more regularly on the stand up.