Relax hardware labelling to include dash and underscore
quattor/aquilon pull request #65
Opened 2017-06-05 12:44 UTC by jrha

Our naming scheme for network devices (switches, routers) uses dashes and underscores to separate fields.

Change-Id: I0d42aa3469b0b515fb8377911ab9e07f5511b4f2

2017-06-05 12:44 UTC, jrha commented
Cherry picked from #37.

2017-06-12 14:57 UTC, urbonegi commented
unittests needs refactoring as a result of this change. I.E. this:
FAIL: test_200_reject_bad_label_explicit (broker.test_add_netdev.TestAddNetworkDevice)

Let me validate that we are ok with relaxed validation though.

2017-06-22 10:10 UTC, urbonegi commented
We agreed to drop the hardware label regex validation at all. I suggest this PR should be closed and the work to remove validation/update unittest to be done internally in MS and synced to upstream. Please close the PR if that is ok.

2017-06-22 10:12 UTC, urbonegi requested changes
We will drop label validations from hardware entity model at all. Code changes to be done in MS and synced to upstream. Please ack and close PR.

2017-06-22 11:19 UTC, jrha commented
Ok thanks!

2017-06-22 11:19 UTC, closed without merging